name: intargram
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.3.0
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  firebase_storage: ^10.3.2
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.1+1
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  uuid: ^3.0.6
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.17.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
     - family: Muli
       fonts:
         - asset: assets/fonts/muli/Muli.ttf
         - asset: assets/fonts/muli/Muli-Bold.ttf
           weight: 700
         - asset: assets/fonts/muli/Muli-Light.ttf
           weight: 300
